name: minha_estante
description: Organizador de leitura — Livros, Mangás e Quadrinhos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  provider: ^6.1.1

  # Scanner de ISBN (código de barras)
  mobile_scanner: ^5.2.3

  # OCR — leitura de texto da capa
  google_mlkit_text_recognition: ^0.13.0

  # Câmera e galeria para foto da capa
  image_picker: ^1.1.2

  # Banco local
  sqflite: ^2.3.2
  path: ^1.9.0

  # HTTP
  http: ^1.2.1

  # Imagens com cache
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true